FROM node:19.6-alpine

WORKDIR /usr/src/app

COPY package*.json ./

RUN --mount=type=cache,target=/usr/src/app/.npm \
  npm set cache /usr/src/app/.npm && \
  npm ci --only=production

COPY --chown=node:node ./src .

ENV NODE_ENV=production

USER node

EXPOSE 3000

CMD ["node","index.js"]